#!/usr/bin/python3
"""find the two numbers whose products gives the original number"""
from sys import argv


def factorise(number):
    """get the two numbers whose product gives the larger number"""
    m = 2

    if number < 2:
        return
    print()
    print(number, "<- number-now")
    while number % m:
        m += 1
    print("{:.0f}={:.0f}".format(number, number / m, m))
    print(number, "<- number-old")
    print()

    if len(argv) != 2:
        exit()

    try:
        with open(argv[1]) as file:
            line = file.readline()

            while line != "":
                number = int(line.split('\n')[0])
                factorise(number)
                line = file.readline()
    except:
        pass
