#!/usr/bin/python3
"""find the two prime numbers whose product is the argument passed"""
from sys import argv


def factorize(number):
    """"get the two numbers whose product is equal to the argument passed"""
    m = 2

    if number < 2:
        return
    
    while number % m:
        m += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number, number / m, m))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number = int(line.split('\n')[0])
            factorize(number)
            line = file.readline()
except:
    pass
