#!/usr/bin/python3
"""
Find the two prime numbers whose product is equal to the argument passed
"""
import sys


def factorize():
    """
    A function to find the two prime numbers whose product is equal to the argument passed
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line_number in f:
                line_number = int(line_number)
                if line_number % 2 == 0:
                        print("{}={}*{}".format(line_number, line_number // 2, 2))
                        continue
                m = 3
                while m < line_number // 2:
                    if line_number % m == 0:
                        print("{}={}*{}".format(line_number, line_number // m, m))
                        break
                    m = m + 2
                if m == (line_number // 2) + 1:
                    print("{}={}*{}".format(line_number, line_number, 1))
    except (IndexError):
        pass


factorize()
